# Generated by Django 5.0.6 on 2024-07-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='document',
            new_name='aadhar',
        ),
    ]
